layout_spectrum: 0
typography_spectrum: 0.9551972
color:
  saturation: 0.6630824
  lightness: 0.4247312
  brandStrength: 0.3355802
  brandColors:
    - '#FDFDFD'
    - '#282828'
    - '#6A6A6A'
    - '#919191'
    - '#CDCDCD'
  rhythmicContrast: 0.4677419
name: 'Hamilton Barnes, LLC'
