layout_spectrum: 0.7612944
color:
  saturation: 0.8021069
  lightness: 0.5910473
  brandStrength: 0.3355802
  brandColors:
    - '#FDFDFD'
    - '#282828'
    - '#6A6A6A'
    - '#919191'
    - '#CDCDCD'
  rhythmicContrast: 0.3447284
typography_spectrum: 0.7459885
name: 'Hamilton Barnes, LLC'
